[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[rpc_endpoints]
Sepolia = "${SEPOLIA_RPC_URL}"
Local = "${LOCAL_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
